#!/usr/bin/python3
"""Take a picture using Pi camera"""
from os import system, makedirs
from datetime import datetime
from os.path import join


BASE_IMAGE_DIR = '/home/pi/Pi-Timelapser/images/'


current_time = datetime.now()
image_dir = join(BASE_IMAGE_DIR, current_time.strftime("%Y-%m-%d"))
output_filename = join(image_dir, f'image-{current_time.strftime("%Y-%m-%d-%H-%M-%S")}.jpg')

makedirs(image_dir, exist_ok=True)
system(f'raspistill -o {output_filename} --annotate 12 --quality 100')
