#!/usr/bin/python3
"""
Create timelapse video, upload, then delete
"""
import logging
from datetime import datetime, timedelta
from glob import glob
from os import system
from os.path import join, getmtime
from smtplib import SMTP_SSL, SMTP_SSL_PORT
from email.message import EmailMessage
from ftplib import FTP

logging.basicConfig(level=logging.INFO)

IMAGE_BASE_DIR = '/home/pi/Pi-Timelapser/images/'
RESOLUTION = '2592:1944'  # 3280:2464 for Pi Cam v2

# TODO: create cpanel page for content
# start with just dir listing? php script to list contents/display? 


def make_timelapse_video(date):
    image_dir = join(IMAGE_BASE_DIR, date)
    images = glob(join(image_dir, '*.jpg'))
    images.sort(key=getmtime)
    image_list_file = join(image_dir, 'image-list.txt')
    with open(image_list_file, 'w') as temp_file:
        for image in images:
            temp_file.write(f'{image}\n')
    video_path = join(IMAGE_BASE_DIR, date, f'timelapse-{date}.avi')
    command = f'mencoder -nosound -ovc lavc -lavcopts vcodec=mpeg4:aspect=16/9:vbitrate=8000000 -vf scale={RESOLUTION} -o "{video_path}" -mf type=jpeg:fps=24 "mf://@{image_list_file}"'
    logging.info(f'Command: {command}')
    system(command)



# def delete_content(date):
#     pass

# def ftp_upload(date):
#     with FTP('ftp.example.com', 'user', 'pass') as ftp:
#         with open('image.png', 'rb') as image_file:
#             ftp.storbinary('STOR image.png', image_file)


# def sendmail():
#     from_email = 'John Leon <nanodano@devdungeon.com>'  # or simply the email address
#     to_emails = ['nanodano@devdungeon.com', 'admin@devdungeon.com']
#
#     email_message = EmailMessage()
#     email_message.add_header('To', ', '.join(to_emails))
#     email_message.add_header('From', from_email)
#     email_message.add_header('Subject', 'Hello!')
#     email_message.add_header('X-Priority', '2')  # Urgent/High priority
#     email_message.set_content('Hello, world!')
#
#     smtp_server = SMTP_SSL('mail.example.com', port=SMTP_SSL_PORT)
#     smtp_server.set_debuglevel(1)  # Show SMTP server interactions
#     smtp_server.login('user@example.com', 'pass')
#     smtp_server.sendmail(from_email, to_emails, email_message.as_bytes())
#
#     smtp_server.quit()


def main():
    yesterdays_date = (datetime.now() - timedelta(days=1)).strftime('%Y-%m-%d')
    print(yesterdays_date)
    logging.info('Making timelapse video')
    make_timelapse_video(yesterdays_date)
    # ftp_upload(yesterdays_date)
    # delete_content(yesterdays_date)
    # sendmail()


if __name__ == '__main__':
    main()
