#!/usr/bin/python3
"""
Create timelapse video, upload, then delete
"""
import logging
from datetime import datetime, timedelta
from glob import glob
from os import system, remove
from os.path import join, getmtime, basename
from shutil import rmtree
from smtplib import SMTP_SSL, SMTP_SSL_PORT
from email.message import EmailMessage
from ftplib import FTP

logging.basicConfig(level=logging.INFO)

IMAGE_BASE_DIR = '/home/pi/Pi-Timelapser/images/'
RESOLUTION = '2592:1944'  # 3280:2464 for Pi Cam v2
FTP_DESTINATION = 'cammy-timelapse'

# TODO: create cpanel page for content
# start with just dir listing? php script to list contents/display? 


def make_timelapse_video(date):
    image_dir = join(IMAGE_BASE_DIR, date)
    images = glob(join(image_dir, '*.jpg'))
    images.sort(key=getmtime)
    image_list_file = join(image_dir, 'image-list.txt')
    with open(image_list_file, 'w') as temp_file:
        for image in images:
            temp_file.write(f'{image}\n')
    video_path = join(IMAGE_BASE_DIR, date, f'timelapse-{date}.avi')
    command = f'mencoder -nosound -ovc lavc -lavcopts vcodec=mpeg4:aspect=16/9:vbitrate=8000000 -vf scale={RESOLUTION} -o "{video_path}" -mf type=jpeg:fps=24 "mf://@{image_list_file}"'
    logging.info(f'Command: {command}')
    system(command)



def delete_content(date):
    rmtree(join(IMAGE_BASE_DIR, date))


def ftp_upload(date):
    #logging.debug('Connecting to FTP _ as _')
    with FTP('ftp.example.com', 'user', 'pass') as ftp:
        # Move in to target dir, ensuring it exists
        try:
            logging.debug(f'Changing FTP dir to {FTP_DESTINATION}')
            ftp.cwd(FTP_DESTINATION)
        except Exception:
            logging.warning(f'Could not change FTP dir to {FTP_DESTINATION}. Trying to create.')
            try:
                logging.debug(f'Trying to create FTP dir {FTP_DESTINATION}')
                ftp.mkd(FTP_DESTINATION)
            except Exception as e:
                logging.error(f"Error creating/moving to the FTP destination: {FTP_DESTINATION}")
                raise e

        try:
            logging.debug(f'Trying to create FTP dir to {date}')
            ftp.mkd(date)
        except Exception as e:
            logging.warning(f'Error creating daily folder for upload. May already exist. {e}')

        try:
            logging.debug(f'Trying to change FTP dir to {date}')
            ftp.cwd(date)
        except Exception as e:
            logging.error(f'Could not move to FTP dir {date}. {e}')
            raise e

        # Upload all files
        for local_filename in glob(join(IMAGE_BASE_DIR, date, '*')):
            with open(local_filename, 'rb') as local_file:
                ftp.storbinary(f'STOR {basename(local_filename)}', local_file)


# def sendmail(subject="Pi-Timelapser", body=None):
#     from_email = 'John Leon <nanodano@devdungeon.com>'  # or simply the email address
#     to_emails = ['nanodano@devdungeon.com', 'admin@devdungeon.com']
#
#     email_message = EmailMessage()
#     email_message.add_header('To', ', '.join(to_emails))
#     email_message.add_header('From', from_email)
#     email_message.add_header('Subject', 'Hello!')
#     email_message.add_header('X-Priority', '2')  # Urgent/High priority
#     email_message.set_content('Hello, world!')
#
#     smtp_server = SMTP_SSL('mail.example.com', port=SMTP_SSL_PORT)
#     smtp_server.set_debuglevel(1)  # Show SMTP server interactions
#     smtp_server.login('user@example.com', 'pass')
#     smtp_server.sendmail(from_email, to_emails, email_message.as_bytes())
#
#     smtp_server.quit()


def main():
    yesterdays_date = (datetime.now() - timedelta(days=1)).strftime('%Y-%m-%d')
    print(yesterdays_date)
    logging.info('Making timelapse video')
    make_timelapse_video(yesterdays_date)
    try:
        ftp_upload(yesterdays_date)
    except Exception as e:
        # TODO Email me error
        logging.error("Error uploading over FTP. Aborting and not deleting content.")
        raise e

    delete_content(yesterdays_date)
    # sendmail()


if __name__ == '__main__':
    main()
